package com.ns.net.common.model.enums;

public enum DagType {

    STATIC(1, "User should plan a static dag"),
    DYNAMIC(2, "Dag would be dynamically generated by job dependencies");

    private int code;
    private String desc;

    DagType(int code, String desc) {
        this.code = code;
        this.desc = desc;
    }

    public static DagType of(int code) {
        for(DagType dagType : DagType.values()) {
            if(dagType.code == code) {
                return dagType;
            }
        }
        throw new IllegalArgumentException("unsupported dag type " + code);
    }
    
    public int getCode() {
        return this.code;
    }
}
